[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
argon2 = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls", "macros", "runtime-tokio-rustls", "postgres", "chrono", "json"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
pdfium-render = "0.9"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
async-stripe = { version = "1.0.0-rc.5", features = ["default"] }
stripe-checkout = { package = "async-stripe-checkout", version = "1.0.0-rc.3", features = ["checkout_session"] }
stripe-shared = { package = "async-stripe-shared", version = "1.0.0-rc.3" }
tokio = { version = "1", features = ["full"] }
rand_core = "0.10.0"
rand = "0.8" 
sha2 = "0.10"
hex = "0.4"
futures-util = "0.3"
actix-rt= "2"
hmac = "0.12" 
resend-rs = "0.25.1"
[dev-dependencies]
serial_test = "3"

[lib]
name = "backend"
path = "src/lib.rs"

[env]
JWT_SECRET = { value = "test-jwt-secret-that-is-long-enough", force = true }
