use actix_web::{HttpResponse, Responder, web};

use crate::auth_context::AuthUser;
use crate::db::Db;
use crate::models::engagement::Engagement;
use crate::models::engagement_milestone::EngagementMilestone;

pub async fn generate_for_engagement(
    db: web::Data<Db>,
    auth: AuthUser,
    path: web::Path<i64>,
) -> impl Responder {
    let engagement_id = path.into_inner();

    let engagement = match Engagement::find_for_user(db.pool.as_ref(), engagement_id, auth.id).await
    {
        Ok(item) => item,
        Err(err) => return HttpResponse::NotFound().body(err.to_string()),
    };

    let milestones =
        match EngagementMilestone::for_engagement(db.pool.as_ref(), engagement_id).await {
            Ok(items) => items,
            Err(err) => return HttpResponse::InternalServerError().body(err.to_string()),
        };

    let (contract_type, body) = render_contract_for_engagement(&engagement, &milestones);

    HttpResponse::Ok().json(serde_json::json!({
        "engagement_id": engagement_id,
        "contract_type": contract_type,
        "body": body
    }))
}

fn render_contract_for_engagement(
    engagement: &Engagement,
    milestones: &[EngagementMilestone],
) -> (String, String) {
    match engagement.engagement_type.as_str() {
        "consulting" => (
            "consulting_services".to_string(),
            render_consulting_contract(engagement, milestones),
        ),
        "field_services" => (
            "field_services".to_string(),
            render_field_services_contract(engagement, milestones),
        ),
        "creative" => (
            "creative_services".to_string(),
            render_creative_contract(engagement, milestones),
        ),
        "maintenance" => (
            "maintenance_retainer".to_string(),
            render_maintenance_contract(engagement, milestones),
        ),
        "rental" => (
            "rental".to_string(),
            render_rental_contract(engagement, milestones),
        ),
        _ => (
            "software_services".to_string(),
            render_software_contract(engagement, milestones),
        ),
    }
}

fn milestone_text(milestones: &[EngagementMilestone]) -> String {
    let text = milestones
        .iter()
        .map(|m| {
            format!(
                "- {}: {} — ${:.2}",
                m.title,
                m.description
                    .clone()
                    .unwrap_or_else(|| "No description provided".to_string()),
                m.amount_cents as f64 / 100.0
            )
        })
        .collect::<Vec<String>>()
        .join("\n");

    if text.is_empty() {
        "No milestones specified.".to_string()
    } else {
        text
    }
}

fn common_header(
    title: &str,
    engagement: &Engagement,
    milestones: &[EngagementMilestone],
) -> String {
    format!(
        r#"
{heading}

Engagement:
"{title}"

Contractor / Provider:
{contractor_name}
{contractor_email}

Role:
{role}

Scope:
{scope_of_work}

Deliverables / Included Work:
{deliverables}

Reference / Work Location:
{repo_url}

Total Compensation:
${amount:.2} {currency}

Milestones:
{milestones}
"#,
        heading = title,
        title = engagement.title,
        contractor_name = engagement.contractor_name,
        contractor_email = engagement.contractor_email,
        role = engagement.role,
        scope_of_work = engagement.scope_of_work,
        deliverables = engagement
            .deliverables
            .clone()
            .unwrap_or_else(|| "No deliverables specified".to_string()),
        repo_url = engagement
            .repo_url
            .clone()
            .unwrap_or_else(|| "Not specified".to_string()),
        amount = engagement.amount_cents as f64 / 100.0,
        currency = engagement.currency.to_uppercase(),
        milestones = milestone_text(milestones),
    )
}

fn platform_footer() -> &'static str {
    "Generated by Consult Ops."
}

fn render_consulting_contract(e: &Engagement, m: &[EngagementMilestone]) -> String {
    format!(
        r#"{header}

Terms:

1. Advisory Services
The Contractor agrees to provide consulting, advisory, analysis, planning, implementation support, or strategic guidance as described in the scope.

2. Cooperation and Information
The hiring organization agrees to provide reasonable access to information, stakeholders, systems, or documents needed to perform the consulting work.

3. Recommendations
Recommendations, analysis, and plans are based on information available during the engagement. The Contractor does not guarantee a particular financial, operational, legal, or business outcome unless expressly agreed in writing.

4. Deliverables
Deliverables may include reports, roadmaps, assessments, meeting notes, implementation plans, presentations, or other advisory materials described above.

5. Review and Acceptance
The hiring organization may review deliverables before approving a milestone or final payment.

6. Independent Contractor Status
The Contractor is an independent contractor and is not an employee, partner, or agent of the hiring organization.

7. Confidentiality
The Contractor agrees not to disclose private business, client, financial, operational, or technical information encountered during the engagement.

8. Payment
Payment is tied to the agreed engagement amount and/or approved milestones. Payment records may be tracked through the platform.

9. Completion
The engagement is complete when the agreed consulting deliverables or milestones are approved and payment has been recorded.

{footer}
"#,
        header = common_header("CONSULTING SERVICES AGREEMENT", e, m),
        footer = platform_footer(),
    )
}

fn render_field_services_contract(e: &Engagement, m: &[EngagementMilestone]) -> String {
    format!(
        r#"{header}

Terms:

1. Field Services
The Contractor agrees to perform field services, inspections, installations, operational tasks, on-site work, or service visits described in the scope.

2. Site Access
The hiring organization is responsible for providing reasonable site access, instructions, contacts, safety requirements, and any required authorization.

3. Safety and Compliance
The Contractor agrees to follow applicable site rules, safety instructions, lawful operating procedures, and reasonable client requirements communicated before or during the engagement.

4. Completion Evidence
Deliverables may include checklists, photos, service notes, inspection results, incident reports, completion summaries, or client sign-off.

5. Equipment and Materials
Unless otherwise specified, each party is responsible for equipment, materials, credentials, or access assigned to them for the field work.

6. Incident Reporting
The Contractor should promptly report material issues, unsafe conditions, blocked access, equipment damage, incomplete work, or other exceptions affecting completion.

7. Review and Acceptance
The hiring organization may review submitted evidence or field reports before approving a milestone or final payment.

8. Payment
Payment is tied to the agreed engagement amount and/or approved milestones. Payment records may be tracked through the platform.

9. Completion
The engagement is complete when the field work and required completion evidence are submitted, approved, and payment has been recorded.

{footer}
"#,
        header = common_header("FIELD SERVICES AGREEMENT", e, m),
        footer = platform_footer(),
    )
}

fn render_creative_contract(e: &Engagement, m: &[EngagementMilestone]) -> String {
    format!(
        r#"{header}

Terms:

1. Creative Services
The Contractor agrees to produce creative, design, content, media, brand, marketing, writing, video, or related assets according to the approved scope or brief.

2. Creative Brief
The hiring organization is responsible for providing reasonable brand guidance, reference materials, requirements, deadlines, and feedback needed to complete the work.

3. Revisions and Approval
Unless otherwise specified, reasonable revisions may be requested during review. Major changes outside the original scope may require a new milestone or agreement.

4. Deliverables
Deliverables may include drafts, final files, exported assets, source files, copy, designs, campaign materials, media files, or documentation described above.

5. Usage Rights
Unless otherwise specified in writing, accepted and paid deliverables created specifically for this engagement may be used by the hiring organization for its business purposes after full payment.

6. Third-Party Assets
Any stock media, fonts, templates, licensed materials, or third-party assets should be disclosed when applicable. Licensing restrictions remain subject to the original license terms.

7. Attribution
Attribution, portfolio usage, or public display rights should be agreed in writing when relevant.

8. Payment
Payment is tied to the agreed engagement amount and/or approved milestones. Payment records may be tracked through the platform.

9. Completion
The engagement is complete when the agreed creative deliverables are approved and payment has been recorded.

{footer}
"#,
        header = common_header("CREATIVE SERVICES AGREEMENT", e, m),
        footer = platform_footer(),
    )
}
fn render_maintenance_contract(e: &Engagement, m: &[EngagementMilestone]) -> String {
    format!(
        r#"{header}

Terms:

1. Maintenance and Support Services
The Contractor agrees to provide recurring maintenance, monitoring, support, troubleshooting, issue resolution, updates, or operational assistance described in the scope.

2. Coverage
Support coverage is limited to the systems, assets, workflows, tickets, repositories, sites, or operational areas described in this agreement.

3. Response Expectations
Any response times, support windows, escalation procedures, or availability commitments must be stated in the scope or milestones. If not stated, services are provided on a commercially reasonable basis.

4. Excluded Work
Major new features, redesigns, emergency work, out-of-scope systems, unsupported third-party failures, or substantial changes may require a separate agreement or milestone.

5. Maintenance Records
Deliverables may include support summaries, resolved tickets, maintenance logs, monitoring notes, recommendations, or monthly reports.

6. Access and Credentials
Any credentials, system access, repository access, or administrative privileges must be used only for authorized support work and handled with reasonable care.

7. Payment
Payment may be fixed, recurring, milestone-based, or retainer-based as described in this engagement. Payment records may be tracked through the platform.

8. Renewal or Review
The parties may review the maintenance arrangement at the due date, renewal date, or other agreed interval.

9. Completion
The engagement is complete when the agreed maintenance term, milestones, or support obligations are completed and payment has been recorded.

{footer}
"#,
        header = common_header("MAINTENANCE / RETAINER AGREEMENT", e, m),
        footer = platform_footer(),
    )
}

fn render_rental_contract(e: &Engagement, m: &[EngagementMilestone]) -> String {
    format!(
        r#"{header}

Terms:

1. Rental Arrangement
The Provider agrees to make the specified equipment, venue, vehicle, workspace, or rental assets available to the Client for the agreed rental period and permitted use.

2. Rental Period
The rental period begins and ends according to the dates, access instructions, pickup/dropoff terms, booking schedule, or return expectations described in the scope.

3. Permitted Use
The Client may use the rented assets only for lawful purposes consistent with the agreed engagement scope, venue rules, operating instructions, and applicable restrictions.

4. Condition and Return
The Client is responsible for reasonable care of rented property during the rental period and agrees to return all rented assets in substantially the same condition, excluding ordinary wear and tear.

5. Damage, Loss, and Late Return
The Client may be responsible for excessive damage, loss, theft, misuse, missing accessories, cleaning costs, late return fees, or other charges described in the scope or agreed in writing.

6. Access, Rules, and Safety
The Client agrees to follow venue rules, safety instructions, equipment operating requirements, access procedures, capacity limits, and other reasonable restrictions communicated by the Provider.

7. Condition Documentation
The Provider may document the condition of rented assets before and after the rental period for verification, return, and dispute resolution purposes.

8. Payment
Rental fees, deposits, late fees, damage charges, or usage charges may be tracked and processed through the platform as applicable.

9. Cancellation
Cancellation or rescheduling terms should be stated in the scope or agreed in writing. Reservation, preparation, or cancellation fees may apply if specified.

10. Completion
The engagement is complete when the rental period has ended, rented assets have been returned or checked out, and outstanding balances are resolved.

{footer}
"#,
        header = common_header("EQUIPMENT / VENUE RENTAL AGREEMENT", e, m),
        footer = platform_footer(),
    )
}
fn render_software_contract(engagement: &Engagement, milestones: &[EngagementMilestone]) -> String {
    let milestone_text = milestones
        .iter()
        .map(|m| {
            format!(
                "- {}: {} — ${:.2}",
                m.title,
                m.description
                    .clone()
                    .unwrap_or_else(|| "No description provided".to_string()),
                m.amount_cents as f64 / 100.0
            )
        })
        .collect::<Vec<String>>()
        .join("\n");

    format!(
        r#"
SOFTWARE SERVICES AGREEMENT

This Software Services Agreement is entered into for the engagement titled:

"{title}"

Contractor:
{contractor_name}
{contractor_email}

Role:
{role}

Scope of Work:
{scope_of_work}

Deliverables:
{deliverables}

Repository / Work Location:
{repo_url}

Total Compensation:
${amount:.2} {currency}

Milestones:
{milestones}

General Terms:

1. Services
The Contractor agrees to provide software development services related to the scope of work described above.

2. Deliverables
The Contractor will provide code, documentation, configuration, implementation support, or other deliverables described in this agreement.

3. Review and Acceptance
The hiring organization may review submitted work before approving a milestone or final payment.

4. Independent Contractor Status
The Contractor is engaged as an independent contractor and is not an employee, partner, or agent of the hiring organization.

5. Payment
Payment is tied to the agreed engagement amount and/or approved milestones. Payment records may be tracked through the platform.

6. Intellectual Property
Unless otherwise specified in writing, accepted and paid deliverables created specifically for this engagement transfer to the hiring organization upon full payment.

7. Confidentiality
The Contractor agrees not to disclose private business, technical, client, or repository information encountered during the engagement.

8. Tooling and Access
Any repository, system, credential, or deployment access provided for this engagement must be used only for the agreed work.

9. Warranty Disclaimer
Software work may require testing, review, and iteration. The Contractor does not guarantee uninterrupted or error-free operation unless explicitly agreed.

10. Completion
The engagement is complete when the agreed deliverables or milestones are approved and payment has been recorded.

Generated by Consult Ops.
"#,
        title = engagement.title,
        contractor_name = engagement.contractor_name,
        contractor_email = engagement.contractor_email,
        role = engagement.role,
        scope_of_work = engagement.scope_of_work,
        deliverables = engagement
            .deliverables
            .clone()
            .unwrap_or_else(|| "No deliverables specified".to_string()),
        repo_url = engagement
            .repo_url
            .clone()
            .unwrap_or_else(|| "Not specified".to_string()),
        amount = engagement.amount_cents as f64 / 100.0,
        currency = engagement.currency.to_uppercase(),
        milestones = if milestone_text.is_empty() {
            "No milestones specified.".to_string()
        } else {
            milestone_text
        }
    )
}

fn render_generic_contract(
    heading: &str,
    services_clause: &str,
    engagement: &Engagement,
    milestones: &[EngagementMilestone],
) -> String {
    let milestone_text = milestones
        .iter()
        .map(|m| {
            format!(
                "- {}: {} — ${:.2}",
                m.title,
                m.description
                    .clone()
                    .unwrap_or_else(|| "No description provided".to_string()),
                m.amount_cents as f64 / 100.0
            )
        })
        .collect::<Vec<String>>()
        .join("\n");

    format!(
        r#"
{heading}

Engagement:
"{title}"

Contractor:
{contractor_name}
{contractor_email}

Role:
{role}

Scope of Work:
{scope_of_work}

Deliverables:
{deliverables}

Work Location / Reference:
{repo_url}

Total Compensation:
${amount:.2} {currency}

Milestones:
{milestones}

General Terms:

1. Services
{services_clause}

2. Deliverables
The Contractor will provide the deliverables described in this agreement.

3. Review and Acceptance
The hiring organization may review submitted work before approving a milestone or final payment.

4. Independent Contractor Status
The Contractor is an independent contractor and not an employee, partner, or agent.

5. Payment
Payment is tied to the agreed engagement amount and/or approved milestones.

6. Confidentiality
The Contractor agrees not to disclose private business, client, operational, or technical information.

7. Completion
The engagement is complete when agreed deliverables or milestones are approved and payment has been recorded.

Generated by Consult Ops.
"#,
        heading = heading,
        title = engagement.title,
        contractor_name = engagement.contractor_name,
        contractor_email = engagement.contractor_email,
        role = engagement.role,
        scope_of_work = engagement.scope_of_work,
        deliverables = engagement
            .deliverables
            .clone()
            .unwrap_or_else(|| "No deliverables specified".to_string()),
        repo_url = engagement
            .repo_url
            .clone()
            .unwrap_or_else(|| "Not specified".to_string()),
        amount = engagement.amount_cents as f64 / 100.0,
        currency = engagement.currency.to_uppercase(),
        milestones = if milestone_text.is_empty() {
            "No milestones specified.".to_string()
        } else {
            milestone_text
        },
        services_clause = services_clause
    )
}
