use actix_web::{HttpResponse, Responder, web};

use crate::db::Db;
use crate::models::engagement::Engagement;
use crate::models::engagement_milestone::EngagementMilestone;
pub async fn generate_for_engagement(db: web::Data<Db>, path: web::Path<i64>) -> impl Responder {
    let engagement_id = path.into_inner();

    let engagement = match Engagement::find(db.pool.as_ref(), engagement_id).await {
        Ok(item) => item,
        Err(err) => return HttpResponse::NotFound().body(err.to_string()),
    };

    let milestones =
        match EngagementMilestone::for_engagement(db.pool.as_ref(), engagement_id).await {
            Ok(items) => items,
            Err(err) => return HttpResponse::InternalServerError().body(err.to_string()),
        };

    let body = render_software_contract(&engagement, &milestones);

    HttpResponse::Ok().json(serde_json::json!({
        "engagement_id": engagement_id,
        "contract_type": "software_services",
        "body": body
    }))
}

fn render_software_contract(engagement: &Engagement, milestones: &[EngagementMilestone]) -> String {
    let milestone_text = milestones
        .iter()
        .map(|m| {
            format!(
                "- {}: {} — ${:.2}",
                m.title,
                m.description
                    .clone()
                    .unwrap_or_else(|| "No description provided".to_string()),
                m.amount_cents as f64 / 100.0
            )
        })
        .collect::<Vec<String>>()
        .join("\n");

    format!(
        r#"
SOFTWARE SERVICES AGREEMENT

This Software Services Agreement is entered into for the engagement titled:

"{title}"

Contractor:
{contractor_name}
{contractor_email}

Role:
{role}

Scope of Work:
{scope_of_work}

Deliverables:
{deliverables}

Repository / Work Location:
{repo_url}

Total Compensation:
${amount:.2} {currency}

Milestones:
{milestones}

General Terms:

1. Services
The Contractor agrees to provide software development services related to the scope of work described above.

2. Deliverables
The Contractor will provide code, documentation, configuration, implementation support, or other deliverables described in this agreement.

3. Review and Acceptance
The hiring organization may review submitted work before approving a milestone or final payment.

4. Independent Contractor Status
The Contractor is engaged as an independent contractor and is not an employee, partner, or agent of the hiring organization.

5. Payment
Payment is tied to the agreed engagement amount and/or approved milestones. Payment records may be tracked through the platform.

6. Intellectual Property
Unless otherwise specified in writing, accepted and paid deliverables created specifically for this engagement transfer to the hiring organization upon full payment.

7. Confidentiality
The Contractor agrees not to disclose private business, technical, client, or repository information encountered during the engagement.

8. Tooling and Access
Any repository, system, credential, or deployment access provided for this engagement must be used only for the agreed work.

9. Warranty Disclaimer
Software work may require testing, review, and iteration. The Contractor does not guarantee uninterrupted or error-free operation unless explicitly agreed.

10. Completion
The engagement is complete when the agreed deliverables or milestones are approved and payment has been recorded.

Generated by Consult Ops.
"#,
        title = engagement.title,
        contractor_name = engagement.contractor_name,
        contractor_email = engagement.contractor_email,
        role = engagement.role,
        scope_of_work = engagement.scope_of_work,
        deliverables = engagement
            .deliverables
            .clone()
            .unwrap_or_else(|| "No deliverables specified".to_string()),
        repo_url = engagement
            .repo_url
            .clone()
            .unwrap_or_else(|| "Not specified".to_string()),
        amount = engagement.amount_cents as f64 / 100.0,
        currency = engagement.currency.to_uppercase(),
        milestones = if milestone_text.is_empty() {
            "No milestones specified.".to_string()
        } else {
            milestone_text
        }
    )
}
